CREATE TABLE IF NOT EXISTS roles (
    rol_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_name            VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    usr_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usr_rol_id          INTEGER NOT NULL REFERENCES roles(rol_id) ON DELETE CASCADE,
    usr_firstname       VARCHAR(100) NOT NULL,
    usr_lastname        VARCHAR(100) NOT NULL,
    usr_gender          VARCHAR(100) NOT NULL,
    usr_department      VARCHAR(100) NOT NULL,
    usr_jobrole         VARCHAR(100) NOT NULL,
    usr_email           VARCHAR(100) NOT NULL,
    usr_phone           VARCHAR(10),
    usr_profile         TEXT,
    usr_password        VARCHAR(100)
);

INSERT INTO public.roles(rol_name) VALUES
    ('admin'),
	('employee');

INSERT INTO public.users(usr_rol_id, usr_firstname, usr_lastname, usr_gender, usr_department, usr_jobrole, usr_email, usr_phone, usr_profile, usr_password)
VALUES 
(1, 'Somsak',    'Chaiyawat',  'Male',   'IT',          'Software Developer',   'somsak.c@company.com',    '0812345678', 'profile1.jpg',  'hashed_password1'),
(2, 'Siriporn',  'Meechai',    'Female', 'HR',           'HR Manager',           'siriporn.m@company.com',  '0823456789', 'profile2.jpg',  'hashed_password2'),
(2, 'Nattapong', 'Srisuk',     'Male',   'Finance',      'Accountant',           'nattapong.s@company.com', '0834567890', 'profile3.jpg',  'hashed_password3'),
(2, 'Wilaiwan',  'Pongpan',    'Female', 'Marketing',    'Marketing Executive',  'wilaiwan.p@company.com',  '0845678901', 'profile4.jpg',  'hashed_password4'),
(2, 'Kritsana',  'Thongdee',   'Male',   'IT',           'System Analyst',       'kritsana.t@company.com',  '0856789012', 'profile5.jpg',  'hashed_password5'),
(2, 'Pensri',    'Jaidee',     'Female', 'Finance',      'Financial Analyst',    'pensri.j@company.com',    '0867890123', 'profile6.jpg',  'hashed_password6'),
(1, 'Thanakorn', 'Rakdee',     'Male',   'Operations',   'Operations Manager',   'thanakorn.r@company.com', '0878901234', 'profile7.jpg',  'hashed_password7'),
(2, 'Malee',     'Saengchan',  'Female', 'HR',           'Recruiter',            'malee.s@company.com',     '0889012345', 'profile8.jpg',  'hashed_password8'),
(2, 'Prawit',    'Kamolrat',   'Male',   'Marketing',    'SEO Specialist',       'prawit.k@company.com',    '0890123456', 'profile9.jpg',  'hashed_password9'),
(2, 'Sunisa',    'Boonmee',    'Female', 'Operations',   'Logistics Coordinator','sunisa.b@company.com',    '0801234567', 'profile10.jpg', 'hashed_password10');